name: Build and Deploy

on:
  release:
    types: [published]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build package
        run: npm run build
      - name: Deploy page
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
