name: Deploy

on:
  push:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Request Build
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/${{ secrets.BUILD_HOOK }}
